In [41]:
import torch

In [42]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [43]:
df= pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [44]:
df.shape

(569, 33)

In [45]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [46]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

Train Test Split

In [47]:
x_train, x_test, y_train, y_test= train_test_split(df.iloc[:,1:], df.iloc[:,0],test_size=0.2)

In [48]:
scaler = StandardScaler()
x_train= scaler.fit_transform(x_train)
x_test= scaler.transform(x_test)


In [49]:
x_train

array([[-0.05657176,  0.04991514, -0.05007657, ...,  1.00387602,
         0.43746851,  1.20112216],
       [-0.9068343 , -0.40581655, -0.88048022, ..., -0.26812315,
        -0.99255606, -0.07667842],
       [ 1.51162769,  2.13488761,  1.68507085, ...,  1.17631971,
        -0.14257516,  0.91991605],
       ...,
       [-0.42257881,  1.011509  , -0.3944102 , ...,  0.83597031,
         0.76524942,  1.06614323],
       [-0.65062936,  0.48741756, -0.63376905, ..., -0.43618013,
        -0.96684775,  0.86479965],
       [-0.25365248, -1.29449334, -0.26778692, ..., -0.37219444,
        -0.27433023, -0.61546933]])

In [50]:
x_test

array([[-0.08472615, -0.73850068, -0.16240367, ..., -1.07346548,
        -0.58604346, -1.00747065],
       [ 0.1940023 ,  0.18435599,  0.15415453, ..., -0.22138184,
        -0.86401452, -1.02096855],
       [-1.27087054, -0.20757326, -1.26035006, ..., -0.76745355,
         0.42943467,  0.06167499],
       ...,
       [-1.0081901 , -0.10275498, -0.94215801, ..., -0.56082364,
         0.05345068, -0.46530527],
       [-0.70130726,  1.14822851, -0.65255831, ...,  0.21880339,
        -0.1666767 ,  0.87492307],
       [ 1.52288945, -0.28504765,  1.56661681, ...,  1.6391949 ,
         1.18300941,  0.45480114]])

In [51]:
y_train

435    M
534    B
256    M
131    M
322    B
      ..
560    B
278    B
64     M
450    B
384    B
Name: diagnosis, Length: 455, dtype: object

In [52]:
encoder = LabelEncoder()
y_train= encoder.fit_transform(y_train)
y_test= encoder.transform(y_test)


In [53]:
y_train

array([1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1,

In [54]:
x_train_tensor = torch.from_numpy(x_train)
x_test_tensor = torch.from_numpy(x_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [55]:
x_train_tensor.shape

torch.Size([455, 30])

In [56]:
y_train_tensor.shape

torch.Size([455])

Defining the model

In [60]:
class MySimpleNN():

  def __init__(self, X):

    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
     epsilon = 1e-7
     y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)
     loss = -torch.mean(y * torch.log(y_pred) + (1 - y) * torch.log(1 - y_pred))
     return loss

In [58]:
learning_rate = 0.1
epochs = 25

In [61]:

model = MySimpleNN(x_train_tensor)

for epoch in range(epochs):
  y_pred = model.forward(x_train_tensor)

  loss = model.loss_function(y_pred, y_train_tensor)

  loss.backward()

  with torch.no_grad():
    model.weights -=learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  model.weights.grad.zero_()
  model.bias.grad.zero_()

  print(f'Epoch: {epoch +1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.7024756076309244
Epoch: 2, Loss: 3.568770457050475
Epoch: 3, Loss: 3.429911815878376
Epoch: 4, Loss: 3.2869853017648856
Epoch: 5, Loss: 3.1383849077710253
Epoch: 6, Loss: 2.98372353349925
Epoch: 7, Loss: 2.827847058241834
Epoch: 8, Loss: 2.667649896480769
Epoch: 9, Loss: 2.505455089240183
Epoch: 10, Loss: 2.339908843079009
Epoch: 11, Loss: 2.1680500483021365
Epoch: 12, Loss: 1.9980493941523585
Epoch: 13, Loss: 1.8307658190170515
Epoch: 14, Loss: 1.6682372113112205
Epoch: 15, Loss: 1.5168446462711758
Epoch: 16, Loss: 1.3763923508243807
Epoch: 17, Loss: 1.2515456556599263
Epoch: 18, Loss: 1.1440360121487798
Epoch: 19, Loss: 1.0546916963509345
Epoch: 20, Loss: 0.982932416216515
Epoch: 21, Loss: 0.9267557890014579
Epoch: 22, Loss: 0.8835406661355135
Epoch: 23, Loss: 0.8507551381333073
Epoch: 24, Loss: 0.8261125741586359
Epoch: 25, Loss: 0.8076059152902357


In [62]:
model.bias

tensor([-0.1280], dtype=torch.float64, requires_grad=True)

In [63]:
with torch.no_grad():
  y_pred = model.forward(x_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6637426614761353
