<a href="https://colab.research.google.com/github/pankajpandey-dev/pytorch_project/blob/main/pytorch_traningpipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df= pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [ ]:
df.shape

(569, 33)

In [ ]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [ ]:
df.head()

diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

Train Test Split

In [ ]:
x_train, x_test, y_train, y_test= train_test_split(df.iloc[:,1:], df.iloc[:,0],test_size=0.2)

In [ ]:
scaler = StandardScaler()
x_train= scaler.fit_transform(x_train)
x_test= scaler.transform(x_test)


In [ ]:
x_train

array([[-0.23694609, -0.42889384, -0.29860283, ..., -0.9832037 ,
        -0.22702069, -0.70783999],
       [-0.65187393, -1.0847204 , -0.61987755, ..., -0.13728758,
        -0.49511709,  0.85732456],
       [-1.12364119, -0.98419225, -1.1354783 , ..., -1.57761488,
         0.04600999, -0.4165244 ],
       ...,
       [-1.26943432, -0.79271004, -1.28132552, ..., -0.64241603,
        -0.24346833, -0.13571718],
       [ 0.16377188, -0.84536764,  0.05266301, ..., -0.85563531,
        -0.61682956, -1.58528957],
       [ 0.94247207,  0.91866219,  0.80531685, ..., -0.48912211,
        -0.74512109, -1.10657457]])

In [ ]:
x_test

array([[-0.68881955, -0.76638123, -0.65479872, ..., -0.06313751,
        -0.19412543, -0.57415007],
       [-0.42451621, -0.27570808, -0.49210717, ..., -1.48787817,
        -1.10532422, -1.68687056],
       [-0.56377281, -1.09908157, -0.54880271, ..., -0.74441021,
        -0.25991596, -0.06390993],
       ...,
       [ 1.56770579,  2.28536645,  1.73380902, ...,  1.2019535 ,
        -0.14313777,  0.95715415],
       [-0.52114324, -0.96025697, -0.55003522, ..., -0.89452627,
        -0.40136559, -0.26240152],
       [-0.46430381, -0.36905565, -0.40788554, ..., -0.62001968,
        -0.57406572,  0.55374919]])

In [ ]:
y_train

246    B
510    B
185    B
6      M
186    M
      ..
378    B
243    B
234    B
311    B
261    M
Name: diagnosis, Length: 455, dtype: object

In [ ]:
encoder = LabelEncoder()
y_train= encoder.fit_transform(y_train)
y_test= encoder.transform(y_test)


In [ ]:
y_train

array([0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,

In [ ]:
x_train_tensor = torch.from_numpy(x_train)
x_test_tensor = torch.from_numpy(x_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [ ]:
x_train_tensor.shape

torch.Size([455, 30])

In [ ]:
y_train_tensor.shape

torch.Size([455])

Defining the model

In [ ]:
class MySimpleNN():

  def __init__(self, X):

    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, reqiures_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

In [ ]:
learning_rate = 0.1
epochs = 25

In [ ]:
model = MySimpleNN(x_train_tensor)

for epoch in range(epochs):
  y_pred = model.forward(x_train_tensor)

  loss = model.loss_function(y_pred, y_train_tensor)

  loss.backward()

  with torch.no_grad():
    model.weights -=learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  model.weights.grad.zero_()
  model.bias.grad.zero_()

  print(f'Epoch: {epoch +1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.385825141883453
Epoch: 2, Loss: 3.253628812228064
Epoch: 3, Loss: 3.113674797689355
Epoch: 4, Loss: 2.970112524412355
Epoch: 5, Loss: 2.8237552968360116
Epoch: 6, Loss: 2.678502739233024
Epoch: 7, Loss: 2.5277927293771905
Epoch: 8, Loss: 2.372413787646559
Epoch: 9, Loss: 2.20933707722645
Epoch: 10, Loss: 2.044441707588764
Epoch: 11, Loss: 1.8833226330580588
Epoch: 12, Loss: 1.719014907692048
Epoch: 13, Loss: 1.560039966360687
Epoch: 14, Loss: 1.4085686302896512
Epoch: 15, Loss: 1.2705556332881434
Epoch: 16, Loss: 1.1483881176958668
Epoch: 17, Loss: 1.0441779597872813
Epoch: 18, Loss: 0.9591711089268655
Epoch: 19, Loss: 0.8931316742666774
Epoch: 20, Loss: 0.8441587244494966
Epoch: 21, Loss: 0.8091621770418962
Epoch: 22, Loss: 0.7846643176215307
Epoch: 23, Loss: 0.7674877061252333
Epoch: 24, Loss: 0.7551433207357584
Epoch: 25, Loss: 0.7459026497402467


In [ ]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

In [ ]:
with torch.no_grad():
  y_pred = model.forward(x_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5592489838600159
